# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feederpart1', '0005_auto_20161025_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbackform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='quesion',
            name='responses',
            field=models.ManyToManyField(blank=True, to='feederpart1.Response'),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='quesions',
            field=models.ManyToManyField(blank=True, to='feederpart1.Quesion'),
        ),
    ]
