# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feederpart1', '0013_auto_20161031_0227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
