# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feederpart1', '0002_auto_20161024_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
    ]
