# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feederpart1', '0006_auto_20161027_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='feedbackforms',
            field=models.ManyToManyField(blank=True, to='feederpart1.Feedbackform'),
        ),
    ]
