# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feederpart1', '0008_auto_20161029_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackform',
            old_name='quesions',
            new_name='questions',
        ),
    ]
