# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feederpart1', '0015_auto_20161102_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='rating',
            field=models.CharField(max_length=50),
        ),
    ]
